GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic user2@test.com:testing12345

{
    "email": "test4@test.com",
    "firstName": "Test",
    "lastName": null,
    "username": "test4",
    "password": "password123",
    "isVaccinated": true,
    "authorities": "ROLE_USER"
}

###
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic user@test.com:testing123

{
    "email": "test5@test.com",
    "firstName": "Test5",
    "lastName": "LOL",
    "username": "test5",
    "password": "password12345",
    "isVaccinated": true,
    "authorities": "ROLE_USER"
}


###
PUT http://localhost:8080/users/test4@test.com
Content-Type: application/json
Authorization: Basic user2@test.com:testing12345

{
    "email": "test5@test.com",
    "firstName": "Test5",
    "lastName": "LOL",
    "username": "test5",
    "password": "password12345",
    "isVaccinated": true,
    "authorities": "ROLE_USER"
}

###
DELETE http://localhost:8080/users/test5@test.com
Authorization: Basic user2@test.com:testing12345