const data = [
    {
      responsive_id: '',
      id: 95,
      full_name: 'Edwina Ebsworth',
      post: 'Human Resources Assistant',
      email: 'edwinaebsworth@gmail.com',
      city: 'Puzi',
      designation: '01/10/2021',
      next_designation: '20/10/2021',
      age: '27',
      experience: '2 Years',
      status: 1,
    },
    {
      responsive_id: '',
      id: 1,
      full_name: "Korrie O'Crevy",
      post: 'Nuclear Power Engineer',
      email: 'korrieocrevy@gmail.com',
      city: 'Krasnosilka',
      designation: '02/10/2021',
      next_designation: '20/10/2021',
      age: '61',
      experience: '1 Year',
      status: 2,
    },
    {
      responsive_id: '',
      id: 7,
      full_name: 'Eileen Diehn',
      post: 'Environmental Specialist',
      email: 'eileen@gmail.com',
      city: 'Lampuyang',
      designation: '4/10/2021',
      next_designation: '20/10/2021',
      age: '59',
      experience: '9 Years',
      status: 3,
    },
    {
      responsive_id: '',
      id: 11,
      full_name: 'De Falloon',
      post: 'Sales Representative',
      email: 'DefFalloon@yahoo.com',
      city: 'Colima',
      designation: '01/10/2021',
      next_designation: '20/10/2021',
      age: '30',
      experience: '0 Year',
      status: 1,
    },
    {
      responsive_id: '',
      id: 3,
      full_name: 'Stella Ganderton',
      post: 'Operator',
      email: 'stella123@gmail.com',
      city: 'Golcowa',
      designation: '03/10/2021',
      next_designation: '20/10/2021',
      age: '66',
      experience: '6 Years',
      status: 3,
    },
    {
      responsive_id: '',
      id: 5,
      full_name: 'Harmonia Nisius',
      post: 'Senior Cost Accountant',
      email: 'harmonia@gmail.com',
      city: 'Lucan',
      designation: '01/10/2021',
      next_designation: '20/10/2021',
      age: '33',
      experience: '3 Years',
      status: 3,
    },
    {
      responsive_id: '',
      id: 6,
      full_name: 'Genevra Honeywood',
      post: 'Geologist',
      email: 'Genevra345@gmail.com',
      city: 'Maofan',
      designation: '01/10/2021',
      next_designation: '20/10/2021',
      age: '61',
      experience: '1 Year',
      status: 3,
    },
    {
      responsive_id: '',
      id: 4,
      full_name: 'Dorolice Crossman',
      post: 'Cost Accountant',
      email: 'DoroCross789@gmail.com',
      city: 'Paquera',
      designation: '01/10/2021',
      next_designation: '20/10/2021',
      age: '22',
      experience: '2 Years',
      status: 2,
    },
  ]
  
  export default data
  