name: Backend Java CI

on: 
  push:
    branches:
      - "*"
    paths:
      - APICode/**
  pull_request:
    types: [opened, reopened]
    paths:
      - APICode/**

env:
  AZURE_WEBAPP_NAME: swisshack
  AZURE_MYSQL_DB_HOST: ${{ secrets.MYSQL_URL }}
  AZURE_MYSQL_DB_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  AZURE_MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  
jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./APICode
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build & Test with Maven
      run: mvn -B -U verify --file pom.xml
