name: Backend Java CI

on: 
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./APICode
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
