name: main APICode deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: swisshack
  AZURE_MYSQL_DB_HOST: ${{ secrets.MYSQL_URL }}
  AZURE_MYSQL_DB_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  AZURE_MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

defaults:
  run:
    working-directory: ./APICode

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build & Test with Maven
      run: mvn -B -U verify

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build & Push Image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
      
      - name: Deploy to Azure Web App for Container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_API_PUBLISH_PROFILE }}
          images: ${{ secrets.REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
