name: Restaurant Mapper API deployment

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./RestaurantMapper

env:
  AZURE_WEBAPP_NAME: swisshack-restaurantmapper

jobs:
  deploy:
    name: Deploy to Azure Web Services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}

      - name: Deploy to Azure Web App for Container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_MAPPER_PUBLISH_PROFILE }}
          images: ${{ secrets.REGISTRY_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}